### ISSUE TITLE
Chatbot Code Gradio 

### ISSUE THREAD

**Issue by debanshu-mutt** [andreRibeiro1989/medium#2]
So I used the Chatbot Code sample you have with my GPT-2 model and changed the formats accordingly to match how you have sent the output from the function. 
This is the response, context parameter values.
Response in Generate func [('Which is the largest country by area in the world?', 'The largest is the ocean that is legally protected to conserve and manage its biodiversity, ecological processes, and cultural heritage, often used as a tool for sustainable development and environmental protection.')]
Context ['Which is the largest country by area in the world?', 'The largest is the ocean that is legally protected to conserve and manage its biodiversity, ecological processes, and cultural heritage, often used as a tool for sustainable development and environmental protection.']

but with Gradio it's not rendering on the screen the answer, can you help out?

`# Define a function to generate a response given an input
def generate_response(input_text,context=[]):
  import gpt_2_simple as gpt2

  # Start a TensorFlow session and load the GPT-2 model
  sess = gpt2.start_tf_sess()

  gpt2.load_gpt2(sess,run_name="run1",checkpoint_dir="/dbfs/FileStore/test_gpt2/checkpoint/",model_dir = "/dbfs/FileStore/models")
  print('Generate Response Input',input_text)
  context += [input_text]
  updated_input = ""
  updated_input = '[User] : '+input_text+'\n'+'[BOT] :'
  print('Updated Input',updated_input)
  response = gpt2.generate(sess, model_dir="/dbfs/FileStore/models", checkpoint_dir="/dbfs/FileStore/test_gpt2/checkpoint/",truncate= "\n",
                              temperature=1,top_k=10,top_p=0.8,prefix=updated_input,include_prefix=False,
                              return_as_list=True)[0]
  response = response.strip()
  context += [response]
  responses = [(u,b) for u,b in zip(context[::2], context[1::2])]
  sess.close()
  print('Response in Generate func',responses)
  print('Context',context)
  return responses,context`

This is my prediction function.

**Comment by andreRibeiro1989** [comment]
Hey. Sorry the late response. Does the exact code provided here work for you? https://github.com/andreRibeiro1989/medium/blob/main/build_your_own_chatbot/gpt3_gradio_demo.ipynb

Also double check that you are getting the right formats for `responses` and `context`.

responses must be a list of tuples in the following format:
```
[
    [
        "Which is the largest country by area in the world?",
        "The largest country by area in the world is Russia, with a total area of 17,098,242 square kilometers (6,601,668 square miles)."
    ],
    [
        "With which countries does it share a border?",
        "Russia shares a border with the following countries: Norway, Finland, Estonia, Latvia, Lithuania, Poland, Belarus, Ukraine, Georgia, Azerbaijan, Kazakhstan, Mongolia, China, North Korea, and Lithuania."
    ]
]
```

context must be a flat list of responses as below:
```
[
    "Which is the largest country by area in the world?",
    "The largest country by area in the world is Russia, with a total area of 17,098,242 square kilometers (6,601,668 square miles).",
    "With which countries does it share a border?",
    "Russia shares a border with the following countries: Norway, Finland, Estonia, Latvia, Lithuania, Poland, Belarus, Ukraine, Georgia, Azerbaijan, Kazakhstan, Mongolia, China, North Korea, and Lithuania."
]
```

**Comment by debanshu-mutt** [comment]
Hey, everything is working fine now. 
Do you have any piece of code to clear the texbox once output is generated?

**Comment by andreRibeiro1989** [comment]
a bit weird but does the job.
```
import gradio as gr

def get_model_reply(query, context=[]):
    # combines the new question with a previous context
    context += [query]
    response = 'response to: ' + query
    context += [response]
    responses = [(u,b) for u,b in zip(context[::2], context[1::2])]
    return responses, context

# defines a basic dialog interface using Gradio
with gr.Blocks() as dialog_app:
    chatbot = gr.Chatbot()
    state = gr.State([])
    
    with gr.Row():
        txt = gr.Textbox(
            show_label=False, 
            placeholder="Enter text and press enter",
            elem_id='input_text',
        ).style(container=False)

    js = """function(txt, state) {
        t = document.getElementById("input_text");
        t.querySelector("label textarea").value='';
        return [txt, state];
    }"""
    txt.submit(get_model_reply, [txt, state], [chatbot, state], _js=js)

# launches the app in a new local port
dialog_app.launch(debug=True)
```

**Comment by debanshu-mutt** [comment]
Do you know how to style the chatbot? 
Like add a different colour to the userbox and to bot output?

**Comment by andreRibeiro1989** [comment]
You can customise the message by adding HTML or Markdown notation directly. You can also add emojis by writting the HTML entity like this one &#9888;. Also gr.Blocks or gr.Interface accept a `css` argument so you can customise anything through css directly. For more customisation check the Docs: https://gradio.app/docs/#chatbot
